### ISSUE TITLE
Npm start not load application

### ISSUE THREAD

**Issue by ycpatel813** [500tech/react-in-angular#1]
Hi i have clone your application and successfully complete npm install process, but when i use npm start it produce error

E:\yogesh\Angular2\react-in-angular\node_modules\.bin\webpack-dev-server:2
 basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^
SyntaxError: missing ) after argument list
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:545:28)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.runMain (module.js:607:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3

**Comment by borisd** [comment]
Hi

Please clear `node_modules` and try to pull from master, I think I fixed it

https://github.com/500tech/react-in-angular/pull/2
